@startuml

title __MODEL's Class Diagram__\n


    namespace om.example.demo {
      namespace model {
        class com.example.demo.model.Concert {
            - artist : String
            - date : Date
            - genre : String
            - id : int
            - ticketNumber : int
            - time : Date
            - title : String
            + getArtist()
            + getDate()
            + getGenre()
            + getId()
            + getTicketNumber()
            + getTime()
            + getTitle()
            + setArtist()
            + setDate()
            + setGenre()
            + setId()
            + setTicketNumber()
            + setTime()
            + setTitle()
        }
      }
    }

  


    namespace om.example.demo {
      namespace model {
        class com.example.demo.model.Role {
            - id : int
            - login : String
            - role : String
            + getId()
            + getLogin()
            + getRole()
            + setId()
            + setLogin()
            + setRole()
        }
      }
    }

  


    namespace om.example.demo {
      namespace model {
        class com.example.demo.model.Ticket {
            - concertId : int
            - email : String
            - id : int
            - participant : String
            - tickets : int
            + getConcertId()
            + getEmail()
            + getId()
            + getParticipant()
            + getTickets()
            + setConcertId()
            + setEmail()
            + setId()
            + setParticipant()
            + setTickets()
        }
      }
    }

  


    namespace om.example.demo {
      namespace model {
        class com.example.demo.model.User {
            - email : String
            - enabled : boolean
            - id : int
            - password : String
            - username : String
            + getEmail()
            + getId()
            + getPassword()
            + getUsername()
            + isEnabled()
            + setEmail()
            + setEnabled()
            + setId()
            + setPassword()
            + setUsername()
        }
      }
    }

  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
